name = "mo-city-gutters"
main = "src/worker.js"
compatibility_date = "2024-02-17"

[site]
bucket = "./public"

[vars]
GOOGLE_SHEETS_SPREADSHEET_ID = "1VJYPSEtsSmN9yeW1t27iwnZKDusVY9DwbuocN9tVPpA"

[env.production]
route = "mocitygutters.com/*"
